# Generated by Django 4.1.4 on 2023-01-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_description_alter_ad_price_alter_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, max_length=1500, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Текст отзыва'),
        ),
    ]
